export const products = [
  {
    id: "rainbow-glass-beads",
    name: "Rainbow Glass Bead Set",
    price: 299,
    oldPrice: 349,
    rating: 4.5,
    reviews: 127,
    badge: "NEW",
    description: "High quality rainbow glass beads for craft & jewelry.",
    images: ["/assets/rainbowBead.jpeg", "/assets/rainbowBead2.jpeg"],
    sku: "RGB_001",
    category: "Beads",
    stone: "Glass",
  },
  {
    id: "embroidery-thread-collection",
    name: "Embroidery Thread Collection",
    price: 399,
    oldPrice: 499,
    rating: 4.7,
    reviews: 203,
    badge: "NEW",
    description: "Premium embroidery threads with vibrant colors.",
    images: ["/assets/embroideryThread.jpeg", "/assets/embroideryThread2.jpeg"],
    sku: "ET_002",
    category: "Threads",
    stone: "Cotton",
  },
  {
    id: "wooden-bead-assortment",
    name: "Wooden Bead Assortment",
    price: 249,
    oldPrice: 299,
    rating: 4.4,
    reviews: 154,
    description: "Natural wooden beads for handmade crafts.",
    images: ["/assets/woodenBeads.jpeg"],
    sku: "WB_003",
    category: "Beads",
    stone: "Wood",
  },
  {
    id: "diy-jewelry-kit",
    name: "DIY Jewelry Making Kit",
    price: 599,
    oldPrice: 799,
    rating: 4.8,
    reviews: 198,
    badge: "NEW",
    description: "Complete DIY jewelry kit for beginners.",
    images: ["/assets/DIYJewelry.jpeg"],
    sku: "DIY_004",
    category: "Kits",
    stone: "Mixed",
  },
  {
    id: "metallic-charm-collection", // ✅ FIXED
    name: "Metallic Charm Collection",
    price: 349,
    oldPrice: 520,
    rating: 4.8,
    reviews: 98,
    badge: "NEW",
    description: "Metallic charms for premium jewelry designs.",
    images: ["/assets/metallicCharm.jpeg"], // ✅ FIXED
    sku: "MC_005",
    category: "Charms",
    stone: "Metal",
  },
  {
    id: "silk-thread-bundle",
    name: "Silk Thread Bundle",
    price: 449,
    oldPrice: 650,
    rating: 4.8,
    reviews: 142,
    badge: "NEW",
    description: "Smooth silk threads for elegant embroidery.",
    images: ["/assets/silkThread.jpeg"],
    sku: "ST_006",
    category: "Threads",
    stone: "Silk",
  },
  {
    id: "crystal-bead-mix",
    name: "Crystal Bead Mix",
    price: 449,
    oldPrice: 750,
    rating: 4.8,
    reviews: 215,
    badge: "NEW",
    description: "Sparkling crystal beads for luxury crafts.",
    images: ["/assets/crystalBead.jpeg"],
    sku: "CB_007",
    category: "Beads",
    stone: "Crystal",
  },
  {
    id: "craft-tool-essentials",
    name: "Craft Tool Essentials",
    price: 399,
    oldPrice: 580,
    rating: 4.8,
    reviews: 167,
    badge: "NEW",
    description: "Essential tools for all crafting needs.",
    images: ["/assets/craftTool.jpeg"],
    sku: "CT_008",
    category: "Tools",
    stone: "Mixed",
  },
];
